### ISSUE TITLE
firebase_auth 0.14.0+4 update needed

### ISSUE THREAD

**Issue by LOG-TAG** [rajayogan/flutter-phoneAuth#1]
firebase_auth 0.14.0+4 which is Published on Aug 25, 2019 code update needed !

it's asking casting 
```
    final PhoneVerificationCompleted verifiedSuccess = (FirebaseUser user) {
      print('verified');
    };
```

```
  final PhoneVerificationCompleted verifiedSuccess = (FirebaseUser user) {
      print('verified');
    } as PhoneVerificationCompleted;
```

https://github.com/flutter/flutter/issues/27119

**Comment by Sreejith93** [comment]
i have this error

{
	"resource": "/src/flutter_tutorial/mobile_auth/lib/main.dart",
	"message": "The method 'signInWithPhoneNumber' isn't defined for the class 'FirebaseAuth'.\nTry correcting the name to the name of an existing method, or defining a method named 'signInWithPhoneNumber'.",

**Comment by wann2** [comment]
I have changed your source like the below.

final PhoneVerificationCompleted verifiedSuccess = (FirebaseUser user) {
      print('verified');
    } as PhoneVerificationCompleted;

But I got an error like the below.

Unhandled Exception: type '(FirebaseUser) => Null' is not a subtype of type '(AuthCredential) => void' in type cast

**Comment by rajayogan** [comment]
https://github.com/rajayogan/phoneAuth
